### ISSUE TITLE
Local build issues

### ISSUE THREAD

**Issue by daviddao** [piximi/piximi-issues_archived#1]
Developing Piximi locally is not as easy as it requires npm modules to be up to date. It's hard to develop on two different modules at the same time. 
[Yalc](https://github.com/whitecolor/yalc) is only solving this issue partially as it cannot deal with cyclic dependencies. 

I think this issue has highest priority as it really demotivates developing for Piximi (poor @moserle!) 

How should we improve it?

**Comment by moserle** [comment]
This issue seems to be about the same problem:
https://github.com/whitecolor/yalc/issues/95 
(it also provides a potential solution)

**Comment by daviddao** [comment]
Maybe [lerna](https://github.com/lerna/lerna) could be used for this? There is a medium page advertising it: https://medium.com/mitterio/multirepo-to-lerna-js-monorepo-80f6657cb443

**Comment by daviddao** [comment]
We decided to stick with multi repo and use `yarn storybook` to develop
