### ISSUE TITLE
https://piximi.org/ returns 404

### ISSUE THREAD

**Issue by dlogan** [piximi/piximi-issues_archived#2]
On the main page (https://github.com/piximi) the link at the top (https://piximi.org/) returns a 404 message.

**Comment by daviddao** [comment]
That's right, we updated it to piximi.app :)

**Comment by dlogan** [comment]
I see!  Now the link says piximi.app.  However, clicking on it times out my browser.

**Comment by daviddao** [comment]
That's really weird, it works with https://www.piximi.app but strangely it sometimes also time-out for just piximi.app. I assume its a CDN issue @0x00b1 @AlexChrisF

**Comment by dlogan** [comment]
Link works now
