### ISSUE TITLE
Broad Bioimage Benchmark Collection (BBBC) examples

### ISSUE THREAD

**Issue by 0x00b1** [piximi/piximi-issues_archived#3]
We should create example classifiers for appropriate (i.e. classification and recognition) [Broad Bioimage Benchmark Collection (BBBC)](https://data.broadinstitute.org/bbbc/) image sets, e.g., [C. elegans live/dead assay](https://data.broadinstitute.org/bbbc/BBBC010/).

**Comment by daviddao** [comment]
Yes, I looked into it and the problem with BBBC is that (besides C.elegans) we are dealing with whole images. Therefore a single-cell classifier (such as CPA) requires the locations of each cell and the ability to load full images and crop single cells out
